"""add telegram_id

Revision ID: 0f107585b5d3
Revises: 2184f0172791
Create Date: 2026-06-13 21:11:51.019370

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0f107585b5d3'
down_revision: Union[str, Sequence[str], None] = '2184f0172791'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tg_links', 'token',
               existing_type=sa.VARCHAR(length=16),
               type_=sa.VARCHAR(length=128),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tg_links', 'token',
               existing_type=sa.VARCHAR(length=128),
               type_=sa.VARCHAR(length=16),
               existing_nullable=False)
    # ### end Alembic commands ###
